on:
  push:
    branches:
      - Main

name: Deploy Main
jobs:
  web-deploy:
    name: Deploy Main
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v2

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.DEVELOP_FTP_HOST }}
          username: ${{ secrets.DEVELOP_FTP_USER }}
          password: ${{ secrets.DEVELOP_FTP_PASSWORD }}
          server-dir: /
